name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 1.0.18
          cache: true
          cache-bin: true
      - run: bun install
##########
# server #
##########
      - name: Prisma generate
        run: bun prisma generate
        working-directory: ./packages/server
        env:
          DATABASE_URL: 'file:./dev.db'
      - name: server test
        run: bun test
        working-directory: ./packages/server
        env:
          DATABASE_URL: 'file:./dev.db'
##################
# svelte-kit app #
##################
      - name: svelte-kit app test
        run: bun test
        working-directory: ./packages/web-app
