name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 1.1.18
          cache: true
          cache-bin: true
      - run: bun install
      - run: bun prisma generate
        env:
          DATABASE_URL: 'file:./dev.db'
      - run: bun test
        env:
          DATABASE_URL: 'file:./dev.db'
